name: MLOps CI/CD Pipeline

on:
  push:
    branches:
      - main   # Trigger on push to main

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
    
    # Step 1: Get code
    - name: Checkout Code
      uses: actions/checkout@v3

    # Step 2: Setup Python
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9

    # Step 3: Install dependencies
    - name: Install Dependencies
      run: |
        pip install -r requirements.txt

    # Step 4: Run tests
    - name: Run Tests
      run: |
        

    # Step 5: Build Docker image
    - name: Build Docker Image
      run: |
        docker build -t mlops-app .

    # Step 6: Run container (Test Deployment)
    - name: Run Container
      run: |
        docker run -d -p 5000:5000 mlops-app